""" Evolve to version 7.1
"""
allowed = set([
    "APR2007",
    "10 messages for 2010",
    "2010 biodiversity target",
    "Aarhus convention",
    "aboutEEA",
    "absorption capacity",
    "abstraction",
    "accident",
    "acid",
    "acid rain",
    "acidification",
    "acidophilous oak forest",
    "adaptation",
    "adaptation strategy",
    "administrative",
    "advertising",
    "afforestation",
    "age",
    "aggregate extraction",
    "agricultural ecosystem",
    "agriculture",
    "agriculture bioenergy potential",
    "agriculture policy",
    "agri-environment",
    "agri-environment indicators",
    "Agro-ecosystems",
    "agro-ecosystems",
    "air",
    "air conditioning",
    "air emissions",
    "Air pollutant emissions",
    "air pollutant emissions",
    "air pollutant emissions data viewer",
    "air pollutant inventory",
    "Air Pollution",
    "Air pollution",
    "air pollution",
    "air pollution control",
    "air pollution costs",
    "air pollution from energy",
    "Air quality",
    "air quality",
    "air quality data",
    "air quality directive",
    "air quality forecasting",
    "air quality monitoring",
    "air quality zones 2009",
    "air traffic",
    "air transport",
    "air transport emissions",
    "AirBase",
    "airbase",
    "alcohol",
    "algae",
    "alien species",
    "alkalinity",
    "allergy",
    "alpine",
    "alpine coniferous forest",
    "alpine rivers",
    "Alps",
    "alps",
    "alps2009",
    "alternative fuel",
    "alternative water supplies",
    "altimetry",
    "aluminium",
    "ammonia",
    "ammonium",
    "amphibia",
    "amphibian",
    "An Assessment of Assessments",
    "Anatolian",
    "anchovy",
    "ancillary data",
    "animal",
    "annual accounts",
    "annual average",
    "annual fellings",
    "annual management plan",
    "annual report",
    "anoxia",
    "anoxic",
    "anoxic area",
    "anthropogenic",
    "anthropogenic GHG emission",
    "antibiotic",
    "antifouling paint",
    "AOT40",
    "APE",
    "APE001",
    "APE002",
    "APE003",
    "APE004",
    "APE005",
    "APE006",
    "APE2009",
    "APE2010",
    "APE2011",
    "APE3a",
    "appliances",
    "aquaculture",
    "aquatic ecosystems",
    "aquatic habitats",
    "aquatic life",
    "Arctic",
    "arctic",
    "arctic region",
    "arctic sea ice",
    "Arsenic",
    "arsenic",
    "artificial sprawl",
    "artificialisation",
    "asbestos",
    "aspen forest",
    "assessment of assessments",
    "assessment04",
    "assessment05",
    "assessment06",
    "Assessment07",
    "assessment07",
    "Assessment08",
    "assessment08",
    "Assessment09",
    "assessment09",
    "Assessment10",
    "assessment10",
    "assessment11",
    "AssessmentV2",
    "Astana2011",
    "asthma",
    "Atlantic",
    "atmosphere",
    "atmospheric nitrogen",
    "atmospheric pollutants",
    "august2009delivery",
    "automobile manufacturer",
    "avalanche",
    "avalanches",
    "aviation",
    "bactericide",
    "Baltic",
    "baltic sea",
    "baltic sea ecosystem",
    "baltic sea ice",
    "baltic sea salinity",
    "baseline",
    "Baseline2010",
    "Bathing water",
    "bathing water",
    "Bathing water Directive",
    "Bathing water quality",
    "bathing water quality",
    "bathing water report",
    "BDIV",
    "BDIV07d",
    "beach",
    "beach pollution",
    "beach water",
    "bear",
    "beech forest",
    "bees",
    "begining of environmental policy",
    "Belgrade conference",
    "Belgrade07",
    "Benzene",
    "benzene",
    "benzo(a)pyrene",
    "bicycle",
    "bicycle lane",
    "bicycle traffic",
    "bike",
    "biocapacity",
    "biodegradable waste",
    "biodiesel",
    "Biodiversity",
    "biodiversity",
    "biodiversity components",
    "biodiversity conservation",
    "biodiversity indicators",
    "biodiversity information system for europe",
    "biodiversity loss",
    "biodiversity monitoring",
    "biodynamic agriculture",
    "bioenergy",
    "bioenergy crops",
    "bioethanol",
    "biofuel",
    "biofuel directive",
    "biofules",
    "biogas",
    "biogeographic",
    "Biogeographical region",
    "biogeographical region",
    "bio-geographical regions",
    "biomass",
    "Biomass Action Plan",
    "biomass combustion",
    "biomass energy",
    "biome",
    "biomes",
    "bioplant",
    "biotechnology",
    "biotope",
    "biowaste",
    "birch forest",
    "bird",
    "birds",
    "birds directive",
    "BISE",
    "bison",
    "Black Sea",
    "black triangle",
    "Black-tailed godwit",
    "BLOSSOM",
    "blue fish",
    "BOD",
    "BOD5",
    "BOD7",
    "bog",
    "bonito",
    "boreal",
    "boreal forest",
    "bottled water",
    "brackish water",
    "broadleaved evergreen forest",
    "broadleaved-coniferous forest",
    "Budget",
    "buildings",
    "bunker fuels",
    "burden-sharing",
    "burning waste",
    "bus",
    "butterfly",
    "cabon binding",
    "Cadmium",
    "cadmium",
    "CAFE",
    "cancer",
    "CAP",
    "cap and trade",
    "capacity building",
    "capita",
    "car",
    "car industry",
    "car occupancy",
    "car ownership",
    "car sales",
    "car sharing",
    "carbon",
    "carbon capture",
    "carbon capture technology",
    "carbon cycle",
    "carbon dioxide",
    "carbon efficiency",
    "carbon emission",
    "carbon footprint",
    "carbon monoxide",
    "carbon sink",
    "carbon stock",
    "carbon storage",
    "carbon uptake",
    "cardboard",
    "cardboard recycling",
    "cardiovascular",
    "cardiovascular disease",
    "caretta caretta turtle",
    "carpool",
    "cars",
    "carsharing",
    "case studies",
    "Caspian Sea",
    "catchment",
    "cattle",
    "caucasus",
    "CBA",
    "CCPM",
    "CCS",
    "Cd",
    "CDDA",
    "central asia",
    "central heating",
    "Central Park",
    "CEPA",
    "cereal",
    "certification",
    "certified emission reduction",
    "CFC",
    "CFL",
    "CFP",
    "CH4",
    "change",
    "chemical",
    "chemical concentration model",
    "chemical density",
    "chemical elements",
    "compounds",
    "polymers",
    "biological sequences",
    "mixtures and alloys.",
    "chemical industry",
    "chemical policy",
    "chemical pollution",
    "chemical product labelling",
    "chemicals",
    "chemicals information system",
    "childhood cancer",
    "chlorophyll-a",
    "CHP",
    "circles of discovery",
    "Cities",
    "cities",
    "citizen science",
    "CITL",
    "city",
    "CityBEES",
    "civitas",
    "CLC",
    "CLC technical guidelines",
    "CLC1990",
    "CLC2000",
    "CLC2006",
    "CLCchanges",
    "clean water",
    "CLIM",
    "CLIM001",
    "CLIM002",
    "CLIM003",
    "CLIM004",
    "CLIM005",
    "CLIM006",
    "CLIM007",
    "CLIM008",
    "CLIM009",
    "CLIM010",
    "CLIM011",
    "CLIM012",
    "CLIM013",
    "CLIM014",
    "CLIM015",
    "CLIM016",
    "CLIM017",
    "CLIM018",
    "CLIM019",
    "CLIM020",
    "CLIM021",
    "CLIM022",
    "CLIM023",
    "CLIM024",
    "CLIM025",
    "CLIM026",
    "CLIM027",
    "CLIM028",
    "CLIM029",
    "CLIM030",
    "CLIM031",
    "CLIM032",
    "CLIM033",
    "CLIM034",
    "CLIM035",
    "CLIM036",
    "CLIM037",
    "CLIM038",
    "CLIM039",
    "CLIM040",
    "CLIM041",
    "CLIM042",
    "CLIM08",
    "CLIM2008",
    "climate",
    "Climate Action Network",
    "Climate change",
    "climate change",
    "climate change adaptation",
    "climate change adaption",
    "climate change and health",
    "climate change and you (EN)",
    "climate change consequences",
    "climate change impacts",
    "climate change in mountains",
    "climate change mitigation",
    "climate strategy",
    "climatic change",
    "CLRTAP",
    "CO",
    "CO2",
    "CO2 credit",
    "CO2 emissions",
    "CO2 leakage",
    "CO2 transferral",
    "coach",
    "coal",
    "coast",
    "coast_sea",
    "coastal",
    "coastal areas",
    "coastal bathing waters",
    "coastal city",
    "coastal ecosystem",
    "coastal erosion",
    "coastal management",
    "coastal sediment balance",
    "coastal water",
    "Coastal waters",
    "coastline urbanisation",
    "coasts",
    "COD",
    "COD",
    "cod",
    "code list",
    "coffee",
    "combined heat and power",
    "combustion",
    "combustion plant",
    "common agricultural policy",
    "common agricultural policy",
    "common bird",
    "common fisheries policy",
    "common transport policy",
    "community farm",
    "compact fluorescent lamp",
    "compaction",
    "competition for resources",
    "composting",
    "concentration",
    "conductivity",
    "congestion charge",
    "conifer",
    "coniferous forest",
    "conservation",
    "conservation of biodiversity",
    "conservation of species",
    "construction",
    "construction mineral",
    "consumer behaviour",
    "consumer good",
    "consumer prices",
    "consumption",
    "consumption and production patterns",
    "consumption pattern",
    "consumption patterns",
    "consumption trend",
    "container",
    "contaminated land",
    "contaminated soil",
    "contamination",
    "continental",
    "contributing factors",
    "conversion",
    "cooling",
    "COP15",
    "copper",
    "coral acidification",
    "coral reefs",
    "CORILIS",
    "Corilis",
    "corilis",
    "CORINAIR",
    "Corine",
    "Corine Land Cover",
    "corine land cover",
    "cork",
    "corporate communication",
    "corrosion",
    "cost-benefit analysis",
    "costs of adaptation",
    "costs of inaction",
    "Country codes",
    "Candidate countries",
    "European Free Trade Association (EFTA)",
    "European Union (EU)",
    "Country codes",
    "Candidate countries",
    "European Free Trade Association (EFTA)",
    "European Union (EU)",
    "country policy",
    "cover",
    "crop",
    "crop yield",
    "cropland",
    "crops",
    "cross-sectoral adaptation",
    "cryosphere",
    "crysopteris montana",
    "CSI",
    "CSI001",
    "CSI002",
    "CSI003",
    "CSI004",
    "CSI005",
    "CSI006",
    "CSI007",
    "CSI008",
    "CSI009",
    "CSI010",
    "CSI011",
    "CSI012",
    "CSI013",
    "CSI014",
    "CSI015",
    "CSI016",
    "CSI017",
    "CSI018",
    "CSI019",
    "CSI020",
    "CSI021",
    "CSI022",
    "CSI023",
    "CSI024",
    "CSI025",
    "CSI026",
    "CSI027",
    "CSI028",
    "CSI029",
    "CSI030",
    "CSI031",
    "CSI032",
    "CSI033",
    "CSI034",
    "CSI035",
    "CSI036",
    "CSI037",
    "CSI0xx",
    "cultural landscapes",
    "cycle",
    "dam",
    "danube",
    "data centre",
    "data flow",
    "data management",
    "DDT",
    "deadwood",
    "death",
    "decision-making",
    "decomposition",
    "decomposition analysis",
    "decouple",
    "decoupling",
    "deepwater",
    "defoliation",
    "deforestation",
    "degradation",
    "DEM",
    "demand",
    "demography",
    "demolition",
    "density",
    "deposition",
    "desalination",
    "desert",
    "desertification",
    "designated areas",
    "determinand",
    "developed countries",
    "developing countries",
    "development",
    "development of GDP",
    "development of prices",
    "diesel",
    "diet",
    "dietary",
    "diffuse",
    "diffuse contamination",
    "diffuse sources",
    "dike",
    "dioxin",
    "dioxins and furans",
    "direct and indirect pressures",
    "directive",
    "disaster",
    "discharge",
    "disease",
    "diseases",
    "DISMED",
    "displacements",
    "display",
    "disposal",
    "distribution",
    "distribution of species",
    "distribution of waste",
    "DMC",
    "DMC per capita",
    "domestic animals",
    "domestic appliance",
    "domestic material consumption",
    "dominant landscapes types",
    "DPSIR",
    "drinking water",
    "drivers of change",
    "driving tips",
    "drought",
    "droughts",
    "dry matter",
    "dust mites",
    "early warning",
    "earth summit",
    "earthquake",
    "Eastern Europe",
    "ecodesign",
    "Ecodrive",
    "ecodriving",
    "eco-industry",
    "ecolabel",
    "eco-label",
    "ecological diversity",
    "ecological footprint",
    "ecological network",
    "ecology",
    "economic",
    "economic assessment",
    "economic competitiveness",
    "economic damage costs",
    "economic downturn",
    "economic growth",
    "economic megatrends",
    "economic policy instruments",
    "economic unequality",
    "economy",
    "ECOSOC",
    "ecosystem",
    "ecosystem accounting",
    "ecosystem integrity",
    "ecosystem resilience",
    "ecosystem services",
    "ecosystems",
    "ecosystems perspective",
    "eco-technology",
    "ecotourism",
    "eco-village",
    "education",
    "education based travel",
    "EE_F01",
    "EE_F02",
    "EE_F04",
    "EE_F05",
    "EE_F06",
    "EE_F07",
    "EE_F08",
    "EE_F09",
    "EE_F11",
    "EE_F12",
    "EE_F13",
    "EEA",
    "EEA environment policy",
    "EEA general brochure 2009 (BG)",
    "EEA Member Countries",
    "EEA owned data sets",
    "EEA product",
    "EEA Report No 2/2004",
    "EEA role",
    "EEA Signals 2010 - Biodiversity",
    "EEA strategy",
    "EEA target audience",
    "EE-AoA",
    "EETAP",
    "efficiency",
    "eionet",
    "eionet waterbase",
    "eionet-water",
    "electric car",
    "electricity",
    "electricity consumption",
    "electricity generation",
    "electromagnetic field",
    "electronic equipment",
    "electronic waste",
    "elevation",
    "EMAS",
    "emas",
    "EMEP",
    "EMEP model scenarios",
    "EMF",
    "Emission",
    "emission",
    "emission ceiling",
    "emission inventory",
    "emission monitoring",
    "emission offsetting",
    "emission reduction",
    "emission reduction unit",
    "emission trading",
    "emission trading scheme",
    "emission trends",
    "emission trends and projections",
    "emission unit",
    "emissions",
    "emissions for industry",
    "emissions from agriculture",
    "emissions from transport",
    "Emissions Reduction",
    "emissions trading directive",
    "emissions trading scheme",
    "emissions trading system",
    "emissions trends and projections",
    "employment",
    "endangered plant species",
    "endangered species",
    "endemic species",
    "endenism",
    "endocrine disruption",
    "ENER",
    "ENER001",
    "ENER005",
    "ENER006",
    "ENER007",
    "ENER007ENER2011",
    "ENER008",
    "ENER009",
    "ENER01",
    "ENER010",
    "ENER011",
    "ENER012",
    "ENER013",
    "ENER014",
    "ENER015",
    "ENER016",
    "ENER017",
    "ENER018",
    "ENER019",
    "ener02",
    "ENER020",
    "ENER021",
    "ENER022",
    "ENER023",
    "ENER024",
    "ENER025",
    "ENER026",
    "ENER027",
    "ENER028",
    "ENER029",
    "ENER030",
    "ENER031",
    "ENER032",
    "ENER034",
    "ENER035",
    "ENER05",
    "ENER06",
    "ENER07",
    "ENER08",
    "ENER09",
    "ENER11",
    "ENER12",
    "ENER13",
    "ENER15",
    "ENER16",
    "ENER17",
    "ENER18",
    "ENER19",
    "ENER20",
    "ENER2009",
    "ENER2010",
    "ENER2011",
    "ENER21",
    "ENER22",
    "ENER23",
    "ENER24",
    "ENER25",
    "ENER26",
    "ENER27",
    "ENER28",
    "ENER29",
    "ENER30",
    "ENER31",
    "ENER32",
    "ENER34",
    "ENER35",
    "Energy",
    "energy",
    "energy audit",
    "energy certification",
    "energy consumption",
    "energy consumtion",
    "energy crisis",
    "energy demand",
    "energy efficiency",
    "energy efficiency label",
    "energy efficient buildings",
    "energy efficient bulb",
    "energy efficient lighting",
    "energy intensity",
    "energy mix",
    "energy policy",
    "energy price",
    "energy production",
    "energy production emissions",
    "energy production impact",
    "energy productivity",
    "energy use",
    "energy2008",
    "energy-related emission",
    "ENPI-SEIS",
    "enquiries",
    "enteric fermentation",
    "environment",
    "environment for europe",
    "environmental",
    "environmental accounts",
    "environmental agreements",
    "Environmental assessment report No 10",
    "environmental assets",
    "environmental change model",
    "environmental charges",
    "environmental footprint",
    "environmental information system",
    "environmental law",
    "environmental management system",
    "environmental megatrends",
    "environmental model characterisation",
    "environmental model inventory",
    "environmental modelling technique",
    "Environmental policy",
    "environmental policy",
    "environmental politics",
    "environmental pressure",
    "environmental pressure intensity",
    "environmental statement",
    "environmental tax reform",
    "environmental taxes",
    "environmental technology industry",
    "environmental trends",
    "environmental zone",
    "environmentally-compatible bioenergy",
    "environmentally-oriented farming",
    "EOF",
    "EoID",
    "EPER",
    "E-PRTR",
    "erosion",
    "ERU",
    "estuary",
    "ETC/ACC",
    "ETC/NPB",
    "ETC/WTR",
    "ETR",
    "ETS",
    "EU",
    "EU 2020",
    "EU air emission policies",
    "EU cohesion policy",
    "EU coverage",
    "EU emission inventory",
    "EU ETS",
    "EU GHG inventory",
    "EU legislation",
    "EU marine strategy framework directive",
    "EU objective",
    "EU policies",
    "EU strategy",
    "EU waste types",
    "EU-15",
    "EU-27",
    "EUNIS",
    "euroharp",
    "europa",
    "eu",
    "ramon",
    "regions",
    "nomenclature",
    "territorial",
    "units",
    "statistics",
    "classification",
    "statistical regions",
    "nomenclature server",
    "international statistical classifications",
    "Europe",
    "european adaptation strategy",
    "european environment",
    "european neighbourhood",
    "european neighbourhood project",
    "Europe's environment",
    "eurosion",
    "Eurowaternet",
    "eutrophication",
    "evaporation",
    "e-waste",
    "exceedance",
    "exchange of information decision",
    "exhaust gas",
    "exotic species",
    "expansion",
    "expenditure",
    "export",
    "exports",
    "exposure",
    "extensive farming",
    "externalities",
    "extinction",
    "extraction",
    "extreme events",
    "extreme temperatures",
    "extreme weather event",
    "Eye on Earth",
    "facebook",
    "fact sheets",
    "FAIRMODE",
    "FAME",
    "farm",
    "farming",
    "farmland",
    "farmland abandonment",
    "farmland biodiversity",
    "fatty acid methyl ether",
    "felling",
    "fertiliser",
    "fertility",
    "fertilization",
    "financial crisis",
    "financing",
    "fine dust",
    "fine particles",
    "finland",
    "fire",
    "first environmental policies",
    "fiscal reform",
    "FISH",
    "fish",
    "fish catch",
    "fish stock",
    "FISH003",
    "FISH004",
    "FISH005",
    "FISH011",
    "FISH01a",
    "FISH01b",
    "fisheries",
    "fishery",
    "fishing",
    "flame-retardant",
    "FLIS",
    "floating house",
    "flood",
    "flood defence",
    "flood management",
    "flooding",
    "floodplain forest",
    "floods",
    "flora",
    "flowering",
    "fluorinated gases",
    "food",
    "food consumption",
    "food consumption patterns",
    "food processing",
    "food production",
    "Food production and consumption",
    "food transport",
    "Forest",
    "forest",
    "forest biodiversity",
    "forest connectivity",
    "forest conservation",
    "forest creation",
    "forest degradation",
    "forest disturbance",
    "forest ecosystem",
    "forest fires",
    "forest management",
    "forest monitoring",
    "forest stewardship council",
    "forest thinning",
    "forest type",
    "Forest2008",
    "forestry",
    "forestry bioenergy potential",
    "forestry model",
    "forests",
    "formation",
    "forward-looking indicator",
    "forward-looking information and services",
    "fossil",
    "fossil fuel",
    "fossil fuels",
    "fragmentation",
    "fragmentation report 2011",
    "freight",
    "freight activity",
    "freight transport",
    "freight transport intensity",
    "freshwater",
    "freshwater abstraction",
    "freshwater ecosystems",
    "freshwater pollution",
    "freshwater quality",
    "fridge",
    "frost",
    "fruit",
    "fuel",
    "fuel cell",
    "fuel consumption",
    "fuel efficiency",
    "fuel price",
    "fuel switch",
    "fungicide",
    "furan",
    "future environmental challenges",
    "future priorities",
    "garbage",
    "gas",
    "gas exploitation",
    "GDP",
    "gdp",
    "gender",
    "genes",
    "genetic diversity",
    "genetic pollution",
    "genetically modified organism",
    "geographic",
    "geology",
    "geophysical hazards",
    "geospatial data",
    "GHG",
    "GHG emission",
    "GHG emission trend",
    "GHG emissions",
    "GHG inventory",
    "GHG inventory reporting",
    "GHG retrospective",
    "GHG2008",
    "GHG2009",
    "GHG2009",
    "ghg2009-2.1",
    "GHG2010",
    "GHG2011",
    "GIS",
    "GISCO",
    "glacier",
    "glaciers",
    "glass waste",
    "global",
    "global consumption",
    "global governance",
    "global impacts",
    "global megatrends",
    "global monitoring for environment and security",
    "global resource exploitation",
    "global trade",
    "global warming",
    "globalisation",
    "GMES",
    "GMOs",
    "Gothenburg Protocol",
    "governance",
    "GPS",
    "grains",
    "grassland",
    "gravel",
    "gravel extraction",
    "green architecture",
    "green area",
    "green budget",
    "green economy",
    "green growth",
    "green job",
    "green pharmacy",
    "green purchasing",
    "green space",
    "green tax",
    "green technology",
    "green tip",
    "green urban areas",
    "green wall",
    "green week",
    "greenhouse gas",
    "greenhouse gas emission",
    "Greenhouse Gas Emissions",
    "greenhouse gas emissions",
    "greenhouse gas inventory",
    "greenhouse gases",
    "Greenland",
    "greens",
    "GreenX",
    "grid",
    "ground-level ozone",
    "groundwater",
    "groundwater quality",
    "growing season",
    "growth rates",
    "GUA",
    "guidelines",
    "guidelines on monitoring and reporting",
    "habitat",
    "habitat destruction",
    "habitat directive",
    "habitat fragmentation",
    "habitats",
    "habitats directive",
    "halocarbons",
    "harmful algal bloom",
    "hazardous chemical",
    "hazardous substance",
    "hazardous waste",
    "hazards",
    "HCB",
    "HCH",
    "health",
    "health effects",
    "health impact",
    "health target value",
    "heat",
    "heat wave",
    "heath and scrub",
    "heating",
    "heating degree",
    "heavy metal",
    "heavy metals",
    "help",
    "hemiboreal forest",
    "hemisphere",
    "herbicide",
    "hexachlorobenzene",
    "hexachlorocyclohexane",
    "HFC",
    "Hg",
    "hidden costs of production",
    "high emitting households",
    "high nature value",
    "high ozone concentration",
    "high-input farming",
    "HNV",
    "household",
    "household consumption",
    "household energy consumption",
    "household waste",
    "housing",
    "human",
    "human health",
    "hunting",
    "hybrid vehicle",
    "hydrocarbons",
    "hydroelectric dam",
    "hydrological cycle",
    "hydrometeorological hazards",
    "hydropower",
    "hypoxic",
    "iberian lynx",
    "ice",
    "ice cover",
    "ice extend",
    "ice melting",
    "ice road",
    "ICZM",
    "IED",
    "illegal",
    "illegal waste shipment",
    "Image2000",
    "immigration",
    "impact",
    "impacts",
    "import",
    "Import dependency",
    "imports",
    "incineration",
    "income",
    "increment",
    "indicator",
    "indigenous people",
    "indoor pollution",
    "industrial",
    "industrial accident",
    "industrial combustion",
    "industrial effluent",
    "industrial emissions directive",
    "industrial facility",
    "industrial processes",
    "industrial production",
    "industrial waste",
    "industrialisation",
    "industry",
    "information technologies",
    "infrastructure",
    "inland",
    "inland bathing water",
    "inland water",
    "innovation",
    "insect",
    "insecticide",
    "in-shore",
    "insulation",
    "integrated assessment",
    "integrated coastal management",
    "integrated farming",
    "integrated pollution prevention and control",
    "integrated urban management",
    "intelligent irrigation",
    "intensity",
    "intensive farming",
    "invasive",
    "invasive alien species",
    "invasive species",
    "inventions",
    "inventories",
    "inventory",
    "inventory guidebook",
    "invertebrate",
    "IPCC",
    "IPPC",
    "IRENA",
    "iron and steel waste",
    "irrigation",
    "Italy",
    "Jacqueline McGlade",
    "Janez Potocnik",
    "key pollutants",
    "killer slug",
    "kitchen and garden waste",
    "Kulturnat",
    "Kyoto",
    "kyoto",
    "Kyoto gases",
    "Kyoto mechanism",
    "Kyoto Protocol",
    "Kyoto protocol",
    "kyoto protocol",
    "Kyoto targets",
    "kyoto targets",
    "labour",
    "labour productivity",
    "lake",
    "Lakes",
    "lakes",
    "Land",
    "land",
    "land change",
    "land conservation",
    "land conversion",
    "Land Cover",
    "land cover",
    "land cover change",
    "land cover flow",
    "land development",
    "land management",
    "land monitoring",
    "land prices",
    "land sink",
    "land take",
    "Land use",
    "land use",
    "land use change",
    "land use changes",
    "land use planning",
    "land use trends",
    "landfill",
    "landfill directive",
    "landfilling",
    "landing",
    "landscape",
    "landscape changes",
    "landscape fragmentation",
    "landscape management",
    "landscape planning",
    "landscape protection area",
    "landslide",
    "landslides",
    "landuse",
    "LBA",
    "LCA",
    "LCEP",
    "LEAC",
    "Lead",
    "lead",
    "leafing",
    "legal instruments",
    "less favoured areas",
    "LFA",
    "liability and  compensation schemes",
    "LIFE",
    "life",
    "life cycle",
    "life cycle approach",
    "life cycle assessment",
    "life expectancy",
    "life-cycle thinking",
    "lighting",
    "lignite",
    "lindane",
    "literacy",
    "livestock",
    "living area",
    "LME",
    "load",
    "lobster",
    "local emissions",
    "local production",
    "log",
    "loggerhead turtle",
    "logging",
    "long-range transboundary air pollution",
    "long-term perspective",
    "lorry load factor",
    "loss of land",
    "low emitting households",
    "low level ozone",
    "low-carbon economy",
    "low-cost flight",
    "low-input farming",
    "LPG",
    "LRTAP",
    "LRTAP convention",
    "lubricant",
    "LUCAS data quality",
    "LULUCF",
    "lung disease",
    "Lutra lutra",
    "Macaronesia",
    "mackeral",
    "malaria",
    "mammal",
    "management plan",
    "mandrake",
    "manufactured chemicals",
    "manure",
    "maps",
    "marine",
    "marine and coastal",
    "marine ecosystems",
    "marine gas field",
    "marine litter",
    "marine management",
    "marine oil field",
    "marine pollution",
    "marine resources conservation",
    "marine strategy framework directive",
    "marine transport",
    "marine trophic index",
    "marine water",
    "maritime",
    "maritime economy",
    "market-based instrument",
    "marshland",
    "massif",
    "massifs",
    "material flow analysis",
    "material flows",
    "material footprint",
    "material productivity",
    "material resources",
    "materials",
    "MBI",
    "measures",
    "meat",
    "median",
    "Mediterranean",
    "mediterranean",
    "megatrends",
    "Mercury",
    "mercury",
    "mesophytic deciduous forest",
    "metal",
    "metal production",
    "metals",
    "methane",
    "middle-class",
    "migration",
    "milk",
    "Millenium seed bank",
    "mineral",
    "minerals",
    "mining",
    "mire and swamp forest",
    "mitigation",
    "mobile phone",
    "mobile sources",
    "mobility",
    "mobility week",
    "modal split",
    "mode",
    "model",
    "mollusc",
    "monitor",
    "Montreal protocol",
    "mortality",
    "moss",
    "mothers milk",
    "motorisation",
    "motorways",
    "mountain",
    "mountain area",
    "mountain ecosystem",
    "mountain flower",
    "mountain2010",
    "mountainous beech forest",
    "mountains",
    "MSFD",
    "mudflat",
    "multinational emissions trading scheme",
    "municipal",
    "municipal solid waste",
    "municipal waste",
    "municipal waste generation",
    "muscle",
    "mussel",
    "N",
    "N2O",
    "NAMEA",
    "nanotechnology",
    "NAO index",
    "national adaptation strategy",
    "national emission ceilings directive",
    "national emissions ceilings",
    "national focal point",
    "national park",
    "national strategies",
    "native species",
    "Natlan",
    "Natura 2000",
    "natura 2000",
    "Natura 2000 sites",
    "natura2000",
    "natural",
    "natural areas protection",
    "natural capital",
    "natural compost",
    "natural disasters",
    "natural gas",
    "natural hazards",
    "natural heritage",
    "natural materials",
    "natural parc",
    "natural park",
    "natural resource conservation",
    "Natural resources",
    "natural resources",
    "nature",
    "nature and biodiversity",
    "nature capital",
    "nature conservation",
    "nature reserve",
    "near real-time data",
    "NEC",
    "NEC directive",
    "NECD",
    "negative impacts of bioenergy",
    "neigbourhood",
    "neighbourhood",
    "nemoral coniferous forest",
    "net annual increment",
    "network",
    "neurodevelopmental disorder",
    "NGO",
    "NH3",
    "NH4-N",
    "Nickel",
    "nickel",
    "nitrate",
    "nitrates directive",
    "nitrite",
    "nitrogen",
    "nitrogen balance",
    "nitrogen dioxide",
    "nitrogen oxide",
    "nitrogen oxides",
    "nitrous oxide",
    "NMVOC",
    "NMVOC",
    "NO2",
    "NO3-N",
    "nocturnal species",
    "noise",
    "NOISE database",
    "noise exposure",
    "noise indicators",
    "noise reduction",
    "non-governmental",
    "non-hazardous waste",
    "non-methane volatile organic compounds",
    "non-motorised transport",
    "non-renewable energy",
    "non-renewable resource",
    "non-riverine alder forest",
    "non-road transport",
    "non-state actors",
    "North Sea",
    "notified waste",
    "NOX",
    "NOx",
    "nuclear",
    "nuclear accident",
    "nuclear plant",
    "nuclear safety",
    "nutrient",
    "nutrient enrichment",
    "nutrients",
    "NUTS",
    "O3",
    "obsolete chemical",
    "ocean",
    "ocean acidification",
    "ocean acidity",
    "ocean sink",
    "ocean temperature",
    "ODEX",
    "OECD",
    "offshore",
    "off-shore structure",
    "offshore wind energy",
    "OI",
    "OI001",
    "OI003",
    "OI004",
    "OI005",
    "OI006",
    "OI008",
    "OI009",
    "OI011",
    "OI016",
    "OI018",
    "OI019",
    "OI022",
    "OI023",
    "OI025",
    "OI042",
    "OI045",
    "OI047",
    "OI054",
    "OI055",
    "OI0XX",
    "oil",
    "oil discharge",
    "oil exploitation",
    "oil price",
    "oil processing",
    "oil spill",
    "oil spills",
    "old-growth forest",
    "ONE",
    "onshore wind energy",
    "organic",
    "organic agriculture",
    "organic farming",
    "organic food",
    "organic micro-pollutant",
    "organic soils",
    "organic substances",
    "organophosphate",
    "orthophosphate",
    "otter",
    "Our Arctic Challenge",
    "our natural europe",
    "Outlook",
    "outlook indicator",
    "Outlook002",
    "Outlook003",
    "Outlook004",
    "Outlook005",
    "Outlook006",
    "Outlook007",
    "Outlook008",
    "Outlook009",
    "Outlook010",
    "Outlook011",
    "Outlook013",
    "Outlook014",
    "Outlook017",
    "Outlook018",
    "Outlook019",
    "Outlook020",
    "Outlook021",
    "Outlook023",
    "Outlook024",
    "Outlook025",
    "Outlook026",
    "Outlook027",
    "Outlook028",
    "Outlook030",
    "Outlook031",
    "Outlook032",
    "Outlook035",
    "Outlook036",
    "Outlook037",
    "Outlook039",
    "Outlook041",
    "Outlook042",
    "Outlook043",
    "Outlook046",
    "Outlook047",
    "Outlook048",
    "Outlook049",
    "Outlook05",
    "Outlook050",
    "Outlook051",
    "Outlook052",
    "Outlook053",
    "Outlook054",
    "Outlook055",
    "Outlook056",
    "over-abstraction",
    "overcrowding",
    "overfishing",
    "oxidised",
    "oxy-fuel combustion",
    "oxygen",
    "oxygen depletion",
    "Ozone",
    "ozone",
    "ozone air pollution",
    "ozone depleting substance",
    "ozone depletion",
    "ozone health impacts",
    "ozone hole",
    "ozone layer",
    "ozone peak",
    "ozone precursors",
    "ozone station",
    "ozone vegetation impacts",
    "Packaging waste",
    "packaging waste",
    "PAH",
    "pandemics",
    "pan-Europe",
    "pan-european",
    "pan-European environment",
    "Pannonian",
    "paper",
    "paper recycling",
    "paper waste",
    "paraben",
    "parking space",
    "particle emissions",
    "Particulate matter",
    "particulate matter",
    "passenger",
    "passenger car",
    "passenger transport",
    "passenger transport intensity",
    "passive house",
    "pasture",
    "patent",
    "patent genetic resources",
    "pathogenic micro-organism",
    "Pb",
    "PBC",
    "PCB",
    "PCDD/F",
    "PCP",
    "pentachlorophenol",
    "permafrost",
    "persistent organic pollutants",
    "pesticide",
    "pesticides",
    "petrol",
    "petrol emission",
    "PFC",
    "pH",
    "phallates",
    "pharmaceuticals",
    "phenology",
    "phosphate",
    "phosphorus",
    "phthalates",
    "pipeline",
    "plane",
    "plankton",
    "plant",
    "plantation",
    "plastic",
    "plastic waste",
    "PM",
    "PM10",
    "PM10 health impacts",
    "PM2.5",
    "po",
    "point data",
    "point of pollution",
    "polar bears",
    "policies",
    "policy",
    "policy effectiveness evaluation",
    "policy instruments",
    "policy integration",
    "policy measures",
    "policy-making",
    "political megatrends",
    "pollen",
    "pollutant",
    "pollutants",
    "pollution",
    "polychlorinated biphenyls",
    "polycyclic aromatic hydrocarbons",
    "pond",
    "POPs",
    "population",
    "population change",
    "population density",
    "population exposure",
    "population trend",
    "pork",
    "posidonia oceanica",
    "post-socialist transition",
    "potash",
    "potato",
    "poverty",
    "power plant",
    "power shifts",
    "powerplant",
    "precautionary principle",
    "precious metal",
    "precipitation",
    "PRELUDE",
    "pressure",
    "price",
    "price of water",
    "pricing policy",
    "product groups",
    "product use",
    "production",
    "production patterns",
    "productivity",
    "Products",
    "projection",
    "protected area",
    "protected areas",
    "protected species",
    "protection",
    "protocols",
    "public awareness",
    "public health",
    "public opinion",
    "public outreach",
    "public service",
    "public space",
    "public transport",
    "public water supply",
    "publication",
    "PVC",
    "Qol2009",
    "quality of life",
    "quarrrying",
    "radiation",
    "radioactivity",
    "radon",
    "rail",
    "railway",
    "rain",
    "rain water",
    "rainforest",
    "ramsar",
    "ranunculus montanus",
    "rapeseed oil",
    "rare metal",
    "raster data",
    "raw material",
    "raw material consumption",
    "raw materials",
    "RBD",
    "REACH",
    "recession",
    "recreational area",
    "recycled material",
    "recycling",
    "recycling of car",
    "red list",
    "REDD",
    "reduction",
    "reforestation",
    "refugee",
    "regeneration",
    "regeneration of industrial area",
    "registration",
    "reindeer",
    "releases",
    "renewable",
    "renewable energy",
    "renewables",
    "reporting",
    "reporting obligations",
    "reptile",
    "research",
    "reserve",
    "residential",
    "residue",
    "resilience",
    "resource",
    "resource efficiency",
    "Resource Efficiency Roadmap",
    "resource use",
    "resources",
    "respiratory diseases",
    "response",
    "Rhine",
    "rhine",
    "rhone",
    "Rio conference",
    "risk",
    "risk management",
    "risk reduction",
    "River",
    "river",
    "river basin district",
    "river basin management",
    "river navigation",
    "river system",
    "rivers",
    "road",
    "road capacity",
    "road density",
    "road freight",
    "road safety",
    "road traffic",
    "road transport",
    "rock",
    "rock extraction",
    "rockfalls",
    "rocky habitats",
    "rubbish",
    "rumex nivalis",
    "run-off",
    "rural",
    "safe biological limits",
    "safe water",
    "saline intrusion",
    "Salinisation",
    "salinisation",
    "salmon",
    "salt-marsh",
    "sand",
    "sand erosion",
    "sand extraction",
    "sanitation",
    "satellite imagery",
    "satellite observations",
    "saturation",
    "SBL",
    "scenario studies",
    "scenarios",
    "SCP",
    "SCP2007",
    "SE_F02",
    "sea",
    "sea catchment",
    "sea ice",
    "sea level",
    "sea level rise",
    "sea surface",
    "sea surface temperature",
    "sea temperature",
    "seabed habitat",
    "seabed mining",
    "seagrass",
    "seal",
    "SEBI",
    "SEBI001",
    "SEBI002",
    "SEBI003",
    "SEBI004",
    "SEBI005",
    "SEBI006",
    "SEBI007",
    "SEBI008",
    "SEBI009",
    "SEBI01",
    "SEBI010",
    "SEBI011",
    "SEBI012",
    "SEBI013",
    "SEBI015",
    "SEBI016",
    "SEBI017",
    "SEBI018",
    "SEBI019",
    "SEBI02",
    "SEBI020",
    "SEBI021",
    "SEBI022",
    "SEBI023",
    "SEBI024",
    "SEBI025",
    "SEBI026",
    "SEBI03",
    "SEBI04",
    "SEBI05",
    "SEBI06",
    "SEBI07",
    "SEBI08",
    "SEBI09",
    "SEBI10",
    "SEBI11",
    "SEBI12",
    "SEBI13",
    "SEBI15",
    "SEBI16",
    "SEBI17",
    "SEBI18",
    "SEBI19",
    "SEBI20",
    "SEBI2009",
    "SEBI2010",
    "SEBI22",
    "SEBI23",
    "SEBI24",
    "SEBI25",
    "SEBI26",
    "SEBIassessment09",
    "second generation biofuels",
    "sector",
    "sectoral integration",
    "sectors",
    "security",
    "security of energy supply",
    "sediment",
    "seed bank",
    "SEIS",
    "seismic",
    "self-sown exotic forest",
    "semi-natural habitat",
    "service",
    "settlement",
    "sewage",
    "sewage treatment",
    "sewer",
    "sewerage",
    "sewerage network",
    "SF6",
    "Shared Environmental Information System",
    "sheep",
    "shipment",
    "shipping",
    "shopping journey",
    "shrimp",
    "signals 2010",
    "signals2009",
    "Signals2011",
    "signals2011",
    "simulation-based model",
    "SIP",
    "site",
    "ski resort",
    "skin cancer",
    "smog",
    "smoking",
    "snow cover",
    "snowline",
    "SO2",
    "social equity",
    "social inequalities",
    "social media",
    "social megatrends",
    "socio-economy",
    "soer",
    "SOER2010",
    "soer2010",
    "soil",
    "soil conservation",
    "Soil country profiles - Population density",
    "soil functions",
    "soil moisture",
    "soil organic matter",
    "soil protection",
    "soil sealing",
    "solar energy",
    "solid fuels",
    "solvent",
    "SOMO35",
    "sorting waste",
    "sources",
    "SOx",
    "SPA",
    "space heating",
    "spatial analysis",
    "spatial data",
    "spatial planning",
    "special protection area",
    "species",
    "species impoverishment",
    "species richness",
    "specific regions",
    "speed limits",
    "sprat",
    "sprawl",
    "standard",
    "state",
    "State and Outlook 2005",
    "State and Outlook 2005 - Part A",
    "State and Outlook 2005 - Part B",
    "State and Outlook 2005 - Part C",
    "state of the environment",
    "State of the environment report 1-2007",
    "station",
    "status and trends",
    "Stavros Dimas",
    "steel",
    "steppic",
    "storm",
    "storm overflow",
    "storms",
    "strategy analysis",
    "stratified catchment assessment",
    "street",
    "street increment",
    "street lamp",
    "streetlight",
    "subsidies",
    "subsidy",
    "suburbs",
    "sulfur dioxide",
    "sulfur hexafluoride",
    "sulphate",
    "sulphur",
    "sulphur dioxide",
    "sulphur oxides",
    "summer",
    "summer ice",
    "summer ozone episode",
    "summerhouses",
    "sunlight",
    "support scheme",
    "surface temperature",
    "surface water",
    "sustainability",
    "sustainable",
    "sustainable consumption",
    "sustainable consumption and production",
    "sustainable development",
    "sustainable energy production",
    "sustainable farming",
    "sustainable food consumption",
    "sustainable forest management",
    "sustainable forestry",
    "sustainable housing",
    "sustainable industrial policy",
    "sustainable living",
    "sustainable resource management",
    "sustainable tourism",
    "sustainable transport",
    "sustainableuse2005",
    "swimming water",
    "switzerland",
    "swordfish",
    "synthesis",
    "systemic risks",
    "target",
    "tax",
    "tax deduction",
    "taxes",
    "TCM",
    "technological accidents",
    "technological change",
    "technological hazards",
    "technological innovation",
    "technological progress",
    "technologies",
    "technology",
    "teleconference",
    "television",
    "Temperature",
    "temperature",
    "temperature increase",
    "temperature-sensitive species",
    "template",
    "tender",
    "TERM",
    "TERM indicators",
    "TERM_F02",
    "TERM_F03",
    "TERM001",
    "TERM002",
    "TERM003",
    "TERM004",
    "TERM006",
    "TERM007",
    "TERM008",
    "TERM009",
    "TERM01",
    "TERM010",
    "TERM011",
    "TERM012",
    "TERM013",
    "TERM014",
    "TERM015",
    "TERM016",
    "TERM018",
    "TERM019",
    "TERM02",
    "TERM020",
    "TERM021",
    "TERM022",
    "TERM023",
    "TERM024",
    "TERM025",
    "TERM026",
    "TERM027",
    "TERM028",
    "TERM029",
    "TERM03",
    "TERM030",
    "TERM031",
    "TERM032",
    "TERM033",
    "TERM034",
    "TERM035",
    "TERM036",
    "TERM037",
    "TERM038",
    "TERM04",
    "TERM040",
    "TERM09",
    "TERM18",
    "TERM19",
    "TERM20",
    "TERM2009",
    "TERM2010",
    "TERM2011",
    "term2011",
    "TERM21",
    "TERM22",
    "TERM24",
    "TERM25",
    "TERM26",
    "TERM27",
    "TERM29",
    "TERM30",
    "TERM32",
    "terrestrial",
    "terrestrial ecosystem",
    "territorial",
    "territorial cohesion",
    "territory",
    "textile industry",
    "the risk of carbon leakage",
    "the trading system",
    "thematic assessment",
    "thermophilous deciduous forest",
    "threatened species",
    "threats",
    "threats to biodiversity",
    "tide",
    "tipping element",
    "tipping elements",
    "tire",
    "tire pressure",
    "tobacco",
    "TOFP",
    "tourism",
    "tourists",
    "toxic",
    "toxic spills",
    "toxin",
    "tradable carbon unit",
    "tradable permits",
    "trade",
    "trade flows",
    "trading directive",
    "traffic",
    "traffic jam",
    "tram",
    "transboundary issues",
    "transboundary waste shipment",
    "transitional water",
    "Transport",
    "transport",
    "Transport demand",
    "transport demand",
    "transport emissions",
    "transport infrastructure",
    "transport noise",
    "transport price",
    "transport subsidies",
    "trawl",
    "trawling",
    "tree",
    "trend",
    "triazine pesticides",
    "tropical night",
    "tropospheric ozone",
    "TSP",
    "tuna",
    "turtle",
    "twitter",
    "UAA",
    "ultrafine particle",
    "UMZ",
    "UN",
    "UN climate conference",
    "undernourishment",
    "understanding climate change",
    "UNDP",
    "UNECE",
    "UNFCCC",
    "United States",
    "uranium",
    "Urban",
    "urban",
    "urban air quality",
    "urban area",
    "urban atlas",
    "urban beekeeping",
    "urban design",
    "urban ecosystem",
    "urban environment",
    "urban forest",
    "urban growth",
    "urban lifestyle",
    "urban morphological zones",
    "urban planning",
    "urban policy",
    "urban population",
    "urban sprawl",
    "urban structure",
    "urban traffic",
    "urban transport",
    "Urban Waste Water",
    "urban waste water",
    "urbanisation",
    "urbanization",
    "USA",
    "use patterns",
    "UTM",
    "UV",
    "UV rays",
    "UWWT directive",
    "vector data",
    "vegetable",
    "vegetation",
    "vehicle",
    "vertebrates",
    "veterinary medicines",
    "video",
    "videoconferencing",
    "vineyard",
    "violence",
    "volatile organic compounds",
    "volcanic eruptions",
    "volga",
    "vulnerabilities",
    "war",
    "War of Independence",
    "warm",
    "washing machine",
    "Waste",
    "waste",
    "waste bioenergy potential",
    "waste disposal",
    "waste export",
    "waste generation",
    "waste import",
    "waste incineration",
    "waste management",
    "waste policies",
    "waste policy",
    "waste prevention",
    "waste recovery",
    "waste water",
    "waste2008",
    "wastewater",
    "wastewater treatment",
    "Water",
    "water",
    "water abstraction",
    "water account",
    "water assessment",
    "water consumption",
    "water data centre",
    "water demand",
    "water engineering project",
    "water exploitation index",
    "water flow",
    "water footprint",
    "Water Framework Directive",
    "water framework directive",
    "Water Framework Directive Article 5",
    "Water Framework Directive Article 8",
    "water information system for europe",
    "water legislation",
    "water level",
    "water loss",
    "Water management",
    "water management",
    "water pollution",
    "water pollution from agriculture",
    "water protection",
    "water protection directive",
    "Water quality",
    "water quality",
    "water quantity",
    "water resource management",
    "water resources",
    "water scarcity",
    "water security",
    "water services",
    "water shortage",
    "water supply",
    "water temperature",
    "water towers",
    "water transport",
    "water use",
    "Water Watch",
    "waterbase",
    "water-borne diseases",
    "waterway",
    "WB2009",
    "web tool",
    "WEC",
    "WEC005",
    "WEC04e",
    "WEC07b",
    "WEC2d",
    "WEI",
    "welfare",
    "welfare change",
    "well-being",
    "wells",
    "Western Balkans",
    "wetland",
    "WEU",
    "WEU001",
    "WEU002",
    "WEU003",
    "WEU004",
    "WEU005",
    "WEU007",
    "WEU008",
    "WEU009",
    "WEU010",
    "WEU011",
    "WEU013",
    "WEU014",
    "WEU015",
    "WEU016",
    "WFD",
    "What we do",
    "white goods",
    "white-backed woodpecker",
    "WHO",
    "Who we are",
    "WHS",
    "WHS002",
    "WHS003",
    "WHS007",
    "WHS008",
    "WHS009",
    "WHS010",
    "WHS011",
    "WHS012",
    "WHS01a",
    "WHS6_WHS7",
    "wilderness",
    "wildlife",
    "wind",
    "wind energy",
    "wind energy potential",
    "wind speed",
    "windbreak",
    "windmill",
    "windstorms",
    "wine",
    "winter sport",
    "WIR3",
    "WISE",
    "WISE State of the Environment(SoE)",
    "wolf",
    "wood",
    "wood supply",
    "working area",
    "working remit",
    "world",
    "world health organisation",
    "WQ",
    "WQ002",
    "WQ004",
    "WQ005",
    "WQ006",
    "WQ01c",
    "WQ02a",
    "WQ02e",
    "WQ03b",
    "wrapping",
    "WWF",
    "yearbook",
    "youth audience",
    "youtube",
    "zone",
])

import logging
import transaction
from zope.component.hooks import getSite
from Products.CMFCore.utils import getToolByName
logger = logging.getLogger('Products.EEAPloneAdmin')

def _fixKeywords(brain, catalog):
    """ Fix keywords
    """
    doc = brain.getObject()

    canonical = doc.getCanonical()
    original = canonical.getField('subject').getAccessor(canonical)()
    original = [tag for tag in original if tag in allowed]

    mine = doc.getField('subject').getAccessor(doc)()
    if set(mine).symmetric_difference(original):
        doc.getField('subject').getMutator(doc)(original)
        return doc
    return None

def fixKeywords(self):
    """ Fix language independent keywords
    """
    site = getSite()
    catalog = getToolByName(site, 'portal_catalog')
    brains = catalog.unrestrictedSearchResults()
    total = len(brains)

    logger.info('Fixing keywords for %s documents...', total)

    step = 1
    changed = set()
    for index, brain in enumerate(brains):
        try:
            fixed = _fixKeywords(brain, catalog)
        except Exception as err:
            logger.warn("ERROR: %s", brain.getURL())
            logger.exception(err)
            continue

        if not fixed:
            continue

        changed.add((fixed, brain))

        step += 1
        if step % 100 == 0:
            logger.info('Fixing keywords...%s/%s', index, total)
            transaction.commit()

    # Reindex
    logger.info('Reindexing %s changed objects...', len(changed))
    for doc, brain in changed:
        try:
            doc.reindexObject(idxs=['Subject'])
        except Exception:
            catalog.uncatalog_object(catalog.getpath(brain.data_record_id_))
            doc.reindexObject()

    msg = "Fixing keywords for %s documents... DONE" % total
    logger.info(msg)
    return msg
