""" Migration data useful for migrations
"""

def countryDicts():
    """
    :return: a dict with EU countries
    """
    countriesDict = {}
    countriesDict['Greece'] = {'bbox': [],
                    'geometry': {'coordinates': [39, 22], 'type': 'Point'},
                    'properties': {'adminCode1': u'00',
                                   'adminName1': u'',
                                   'center': [39, 22],
                                   'country': u'GR',
                                   'description': u'Greece',
                                   'name': '390903',
                                   'tags': u'independent political entity',
                                   'title': u'Greece'},
                    'type': 'Feature'}
    countriesDict['Poland'] = {'bbox': [],
        'geometry': {'coordinates': [52, 20], 'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [52, 20],
                       'country': u'PL',
                       'description': u'Poland',
                       'name': '798544',
                       'tags': u'independent political entity',
                       'title': u'Poland'},
        'type': 'Feature'},
    countriesDict['Romania'] = {'bbox': [],
        'geometry': {'coordinates': [46, 25], 'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [46, 25],
                       'country': u'RO',
                       'description': u'Romania',
                       'name': '798549',
                       'tags': u'independent political entity',
                       'title': u'Romania'},
        'type': 'Feature'}
    countriesDict['Portugal'] = {'bbox': [],
        'geometry': {'coordinates': [39.5, -8], 'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [39.5, -8],
                       'country': u'PT',
                       'description': u'Portugal',
                       'name': '2264397',
                       'tags': u'independent political entity',
                       'title': u'Portugal'},
        'type': 'Feature'}
    countriesDict['Spain'] = {'bbox': [],
        'geometry': {'coordinates': [40, -4], 'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [40, -4],
                       'country': u'ES',
                       'description': u'Spain',
                       'name': '2510769',
                       'tags': u'independent political entity',
                       'title': u'Spain'},
        'type': 'Feature'}
    countriesDict['United Kingdom'] = {'bbox': [],
        'geometry': {'coordinates': [54.75844423584778,
                                     -2.6953116059303284],
                     'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [54.75844423584778,
                                  -2.6953116059303284],
                       'country': u'GB',
                       'description': u'United Kingdom',
                       'name': '2635167',
                       'tags': u'independent political entity',
                       'title': u'United Kingdom'},
        'type': 'Feature'}
    countriesDict['Netherlands'] = {'bbox': [],
        'geometry': {'coordinates': [52.5, 5.75], 'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [52.5, 5.75],
                       'country': u'NL',
                       'description': u'Netherlands',
                       'name': '2750405',
                       'tags': u'independent political entity',
                       'title': u'Netherlands'},
        'type': 'Feature'}
    countriesDict['Belgium'] = {'bbox': [],
        'geometry': {'coordinates': [50.8333333, 4], 'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [50.8333333, 4],
                       'country': u'BE',
                       'description': u'Belgium',
                       'name': '2802361',
                       'tags': u'independent political entity',
                       'title': u'Belgium'},
        'type': 'Feature'}
    countriesDict['Germany'] = {'bbox': [],
        'geometry': {'coordinates': [51.5, 10.5], 'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [51.5, 10.5],
                       'country': u'DE',
                       'description': u'Germany',
                       'name': '2921044',
                       'tags': u'independent political entity',
                       'title': u'Germany'},
        'type': 'Feature'}
    countriesDict['France'] = {'bbox': [],
        'geometry': {'coordinates': [46, 2], 'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [46, 2],
                       'country': u'FR',
                       'description': u'France',
                       'name': '3017382',
                       'tags': u'independent political entity',
                       'title': u'France'},
        'type': 'Feature'}
    countriesDict['Czechia'] = {'bbox': [],
        'geometry': {'coordinates': [49.75, 15], 'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [49.75, 15],
                       'country': u'CZ',
                       'description': u'Czechia',
                       'name': '3077311',
                       'tags': u'independent political entity',
                       'title': u'Czechia'},
        'type': 'Feature'}
    countriesDict['Italy'] = {'bbox': [],
        'geometry': {'coordinates': [42.8333333, 12.8333333],
                     'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [42.8333333, 12.8333333],
                       'country': u'IT',
                       'description': u'Italy',
                       'name': '3175395',
                       'tags': u'independent political entity',
                       'title': u'Italy'},
        'type': 'Feature'}
    countriesDict['Cyprus'] = {'bbox': [],
        'geometry': {'coordinates': [35, 33], 'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [35, 33],
                       'country': u'CY',
                       'description': u'Cyprus',
                       'name': '146669',
                       'tags': u'independent political entity',
                       'title': u'Cyprus'},
        'type': 'Feature'}
    countriesDict['Estonia'] = {'bbox': [],
        'geometry': {'coordinates': [59, 26], 'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [59, 26],
                       'country': u'EE',
                       'description': u'Estonia',
                       'name': '453733',
                       'tags': u'independent political entity',
                       'title': u'Estonia'},
        'type': 'Feature'}
    countriesDict['Latvia'] = {'bbox': [],
        'geometry': {'coordinates': [57, 25], 'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [57, 25],
                       'country': u'LV',
                       'description': u'Latvia',
                       'name': '458258',
                       'tags': u'independent political entity',
                       'title': u'Latvia'},
        'type': 'Feature'}
    countriesDict['Lithuania'] = {'bbox': [],
        'geometry': {'coordinates': [56, 24], 'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [56, 24],
                       'country': u'LT',
                       'description': u'Lithuania',
                       'name': '597427',
                       'tags': u'independent political entity',
                       'title': u'Lithuania'},
        'type': 'Feature'}
    countriesDict['Finland'] = {'bbox': [],
        'geometry': {'coordinates': [64, 26], 'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [64, 26],
                       'country': u'FI',
                       'description': u'Finland',
                       'name': '660013',
                       'tags': u'independent political entity',
                       'title': u'Finland'},
        'type': 'Feature'}
    countriesDict['Hungary'] = {'bbox': [],
        'geometry': {'coordinates': [47, 20], 'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [47, 20],
                       'country': u'HU',
                       'description': u'Hungary',
                       'name': '719819',
                       'tags': u'independent political entity',
                       'title': u'Hungary'},
        'type': 'Feature'}
    countriesDict['Bulgaria'] = {'bbox': [],
        'geometry': {'coordinates': [43, 25], 'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [43, 25],
                       'country': u'BG',
                       'description': u'Bulgaria',
                       'name': '732800',
                       'tags': u'independent political entity',
                       'title': u'Bulgaria'},
        'type': 'Feature'}
    countriesDict['Malta'] = {'bbox': [],
        'geometry': {'coordinates': [35.916667, 14.433333],
                     'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [35.916667, 14.433333],
                       'country': u'MT',
                       'description': u'Malta',
                       'name': '2562770',
                       'tags': u'independent political entity',
                       'title': u'Malta'},
        'type': 'Feature'}
    countriesDict['Denmark'] = {'bbox': [],
        'geometry': {'coordinates': [56, 10], 'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [56, 10],
                       'country': u'DK',
                       'description': u'Denmark',
                       'name': '2623032',
                       'tags': u'independent political entity',
                       'title': u'Denmark'},
        'type': 'Feature'}
    countriesDict['Iceland'] = {'bbox': [],
        'geometry': {'coordinates': [65, -18], 'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [65, -18],
                       'country': u'IS',
                       'description': u'Iceland',
                       'name': '2629691',
                       'tags': u'independent political entity',
                       'title': u'Iceland'},
        'type': 'Feature'}
    countriesDict['Switzerland'] = {'bbox': [],
        'geometry': {'coordinates': [47.0001583752864,
                                     8.01426887512207],
                     'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [47.0001583752864, 8.01426887512207],
                       'country': u'CH',
                       'description': u'Switzerland',
                       'name': '2658434',
                       'tags': u'independent political entity',
                       'title': u'Switzerland'},
        'type': 'Feature'}
    countriesDict['Sweden'] = {'bbox': [],
        'geometry': {'coordinates': [62, 15], 'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [62, 15],
                       'country': u'SE',
                       'description': u'Sweden',
                       'name': '2661886',
                       'tags': u'independent political entity',
                       'title': u'Sweden'},
        'type': 'Feature'}
    countriesDict['Austria'] = {'bbox': [],
        'geometry': {'coordinates': [47.3333333, 13.3333333],
                     'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [47.3333333, 13.3333333],
                       'country': u'AT',
                       'description': u'Austria',
                       'name': '2782113',
                       'tags': u'independent political entity',
                       'title': u'Austria'},
        'type': 'Feature'}
    countriesDict['Luxembourg'] = {'bbox': [],
        'geometry': {'coordinates': [49.75, 6.1666667], 'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [49.75, 6.1666667],
                       'country': u'LU',
                       'description': u'Luxembourg',
                       'name': '2960313',
                       'tags': u'independent political entity',
                       'title': u'Luxembourg'},
        'type': 'Feature'}
    countriesDict['Ireland'] = {'bbox': [],
        'geometry': {'coordinates': [53, -8], 'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [53, -8],
                       'country': u'IE',
                       'description': u'Ireland',
                       'name': '2963597',
                       'tags': u'independent political entity',
                       'title': u'Ireland'},
        'type': 'Feature'}
    countriesDict['Liechtenstein'] = {'bbox': [],
        'geometry': {'coordinates': [47.1666667, 9.5333333],
                     'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [47.1666667, 9.5333333],
                       'country': u'LI',
                       'description': u'Liechtenstein',
                       'name': '3042058',
                       'tags': u'independent political entity',
                       'title': u'Liechtenstein'},
        'type': 'Feature'}
    countriesDict['Slovakia'] = {'bbox': [],
        'geometry': {'coordinates': [48.6666667, 19.5], 'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [48.6666667, 19.5],
                       'country': u'SK',
                       'description': u'Slovakia',
                       'name': '3057568',
                       'tags': u'independent political entity',
                       'title': u'Slovakia'},
        'type': 'Feature'}
    countriesDict['Norway'] = {'bbox': [],
        'geometry': {'coordinates': [62, 10], 'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [62, 10],
                       'country': u'NO',
                       'description': u'Norway',
                       'name': '3144096',
                       'tags': u'independent political entity',
                       'title': u'Norway'},
        'type': 'Feature'}
    countriesDict['Slovenia'] = {'bbox': [],
        'geometry': {'coordinates': [46.25, 15.1666667],
                     'type': 'Point'},
        'properties': {'adminCode1': u'00',
                       'adminName1': u'',
                       'center': [46.25, 15.1666667],
                       'country': u'SI',
                       'description': u'Slovenia',
                       'name': '3190538',
                       'tags': u'independent political entity',
                       'title': u'Slovenia'},
        'type': 'Feature'}
    return countriesDict
